INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Acura','ILX',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Acura','MDX',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Acura','NSX',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Acura','RDX',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Acura','RLX',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Acura','RLX Sport Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Acura','TLX',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Acura','MDX Sport Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Alfa Romeo','4C Spider',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Alfa Romeo','Giulia',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Alfa Romeo','Stelvio',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Alfa Romeo','4C',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Aston Martin','Vanquish S',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Aston Martin','DB11',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','A3',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','A3 Sportback e-tron',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','A4',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','A4 allroad',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','A5',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','A6',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','A7',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','A8',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','Q3',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','Q7',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','R8',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','RS 3',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','RS 7',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','S3',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','S4',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','S5',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','S6',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','S7',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','S8',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','SQ5',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','TT',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Audi','RS 5',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Bentley','Bentayga',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Bentley','Continental',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Bentley','Mulsanne',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'BMW','3 Series',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'BMW','6 Series',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'BMW','7 Series',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'BMW','i3',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'BMW','M3',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'BMW','M4',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'BMW','M5',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'BMW','M6',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'BMW','X1',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'BMW','X2',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'BMW','X3',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'BMW','X5',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'BMW','X5 M',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'BMW','X6',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'BMW','M2',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'BMW','X6 M',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Buick','Cascada',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Buick','Enclave',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Buick','Encore',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Buick','Envision',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Buick','LaCrosse',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Buick','Regal Sportback',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Buick','Regal TourX',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Cadillac','ATS',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Cadillac','ATS-V',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Cadillac','CT6',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Cadillac','CTS',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Cadillac','CTS-V',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Cadillac','Escalade',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Cadillac','Escalade ESV',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Cadillac','XTS',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Bolt EV',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','City Express',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Colorado Crew Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Colorado Extended Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Corvette',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Silverado 1500 Crew Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Silverado 1500 Regular Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Silverado 2500 HD Crew Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Silverado 3500 HD Crew Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Sonic',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Spark',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Suburban',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Tahoe',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Traverse',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Trax',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Express 2500 Cargo',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Express 2500 Passenger',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Express 3500 Cargo',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Express 3500 Passenger',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Silverado 2500 HD Double Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Silverado 2500 HD Regular Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Silverado 3500 HD Double Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chevrolet','Silverado 3500 HD Regular Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chrysler','300',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chrysler','Pacifica',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Chrysler','Pacifica Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Dodge','Durango',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Dodge','Grand Caravan Passenger',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Dodge','Journey',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'FIAT','124 Spider',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'FIAT','500L',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'FIAT','500X',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'FIAT','500',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'FIAT','500 Abarth',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'FIAT','500c',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'FIAT','500c Abarth',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'FIAT','500e',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','C-MAX Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','EcoSport',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Edge',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Expedition',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Expedition MAX',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Explorer',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','F150 Regular Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','F150 Super Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','F250 Super Duty Crew Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','F250 Super Duty Regular Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','F250 Super Duty Super Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Fiesta',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Flex',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Focus',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Fusion Energi',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Mustang',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Taurus',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Transit 250 Van',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Transit Connect Cargo',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','F350 Super Duty Crew Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','F350 Super Duty Regular Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','F350 Super Duty Super Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','F450 Super Duty Crew Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Transit 150 Van',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Transit 150 Wagon',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Transit 350 HD Van',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Transit 350 Van',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Transit 350 Wagon',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ford','Transit Connect Passenger',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Freightliner','Sprinter 2500 Cargo',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Freightliner','Sprinter 2500 Crew',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Freightliner','Sprinter 2500 Passenger',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Freightliner','Sprinter 3500 Cargo',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Freightliner','Sprinter 3500XD Cargo',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Genesis','G80',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Genesis','G90',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Acadia',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Canyon Crew Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Canyon Extended Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Sierra 1500 Crew Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Sierra 1500 Double Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Sierra 1500 Regular Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Sierra 2500 HD Crew Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Sierra 2500 HD Regular Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Yukon',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Yukon XL',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Savana 2500 Cargo',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Savana 2500 Passenger',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Savana 3500 Cargo',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Savana 3500 Passenger',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Sierra 2500 HD Double Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Sierra 3500 HD Crew Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Sierra 3500 HD Double Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'GMC','Sierra 3500 HD Regular Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Honda','Accord',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Honda','Civic',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Honda','Civic Type R',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Honda','Clarity Plug-in Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Honda','CR-V',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Honda','Fit',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Honda','HR-V',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Honda','Odyssey',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Honda','Pilot',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Honda','Ridgeline',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Honda','Accord Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Honda','Clarity Electric',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Honda','Clarity Fuel Cell',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Hyundai','Accent',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Hyundai','Elantra GT',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Hyundai','Ioniq Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Hyundai','Ioniq Plug-in Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Hyundai','Kona',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Hyundai','Santa Fe',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Hyundai','Santa Fe Sport',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Hyundai','Sonata',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Hyundai','Ioniq Electric',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Hyundai','Sonata Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Hyundai','Sonata Plug-in Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'INFINITI','Q50',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'INFINITI','Q60',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'INFINITI','Q70',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'INFINITI','QX60',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'INFINITI','QX80',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Jaguar','E-PACE',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Jaguar','F-TYPE',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Jaguar','XE',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Jaguar','XF',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Jaguar','XJ',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Jeep','Cherokee',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Jeep','Compass',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Jeep','Grand Cherokee',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Jeep','Renegade',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Jeep','Wrangler',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Jeep','Wrangler Unlimited',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Kia','Cadenza',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Kia','Forte',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Kia','Forte5',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Kia','Niro',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Kia','Optima Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Kia','Optima Plug-in Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Kia','Rio',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Kia','Sedona',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Kia','Sorento',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Kia','Soul',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Kia','Soul EV',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Kia','Stinger',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Kia','Niro Plug-in Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lamborghini','Huracan',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Land Rover','Discovery',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Land Rover','Discovery Sport',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Land Rover','Range Rover',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Land Rover','Range Rover Evoque',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Land Rover','Range Rover Sport',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Land Rover','Range Rover Velar',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lexus','ES',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lexus','GS',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lexus','GX',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lexus','IS',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lexus','LC',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lexus','LS',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lexus','LX',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lexus','NX',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lexus','RC',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lexus','RX',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lincoln','Continental',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lincoln','MKC',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lincoln','MKT',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lincoln','MKX',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lincoln','MKZ',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lincoln','Navigator',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Lincoln','Navigator L',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Maserati','Ghibli',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Maserati','Levante',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Maserati','Quattroporte',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mazda','CX-3',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mazda','CX-5',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mazda','CX-9',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mazda','MAZDA3',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mazda','MAZDA6',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','C-Class',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','E-Class',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','G-Class',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','GLA',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','GLC',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','GLE',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','GLS',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Mercedes-AMG C-Class',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Mercedes-AMG CLA',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Mercedes-AMG E-Class',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Mercedes-AMG G-Class',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Mercedes-AMG GLA',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','S-Class',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','CLS',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','GLC Coupe',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Mercedes-AMG CLS',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Mercedes-AMG GLC Coupe',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Mercedes-AMG GLE',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Mercedes-AMG GLE Coupe',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Mercedes-AMG GT',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Mercedes-AMG S-Class',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Mercedes-AMG SL',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Mercedes-AMG SLC',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Metris Cargo',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Metris Passenger',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Metris WORKER Cargo',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Metris WORKER Passenger',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','SL',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','SLC',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Sprinter 2500 Cargo',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Sprinter 2500 Crew',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Sprinter 2500 Passenger',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Sprinter 3500 Cargo',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mercedes-Benz','Sprinter 3500 XD Cargo',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'MINI','Clubman',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'MINI','Convertible',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'MINI','Hardtop 4 Door',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mitsubishi','Eclipse Cross',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mitsubishi','Mirage',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mitsubishi','Mirage G4',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mitsubishi','Outlander',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mitsubishi','Outlander PHEV',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Mitsubishi','Outlander Sport',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','370Z',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','Armada',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','Frontier Crew Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','Frontier King Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','GT-R',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','LEAF',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','Maxima',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','Murano',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','NV200',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','Pathfinder',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','Rogue Sport',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','Sentra',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','Titan Crew Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','TITAN XD Crew Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','Versa Note',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','Kicks',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','NV1500 Cargo',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','NV2500 HD Cargo',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','NV3500 HD Cargo',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','NV3500 HD Passenger',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','Titan King Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','TITAN Single Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','TITAN XD King Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Nissan','TITAN XD Single Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Porsche','718 Boxster',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Porsche','718 Cayman',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Porsche','911',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Porsche','Cayenne',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Porsche','Macan',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Porsche','Panamera',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ram','1500 Regular Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ram','2500 Crew Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ram','ProMaster City',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ram','2500 Mega Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ram','2500 Regular Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ram','3500 Crew Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ram','3500 Mega Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ram','3500 Regular Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Ram','ProMaster Cargo Van',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'smart','fortwo electric drive',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'smart','fortwo electric drive cabrio',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Subaru','BRZ',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Subaru','Crosstrek',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Subaru','Forester',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Subaru','Impreza',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Subaru','Outback',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Subaru','WRX',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Tesla','Model 3',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Tesla','Model S',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Tesla','Model X',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','4Runner',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Avalon',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Avalon Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Camry Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Corolla iM',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Highlander',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Highlander Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Land Cruiser',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Prius',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Prius c',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Prius Prime',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','RAV4',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','RAV4 Hybrid',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Sequoia',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Sienna',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Tacoma Access Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Tacoma Double Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Tundra CrewMax',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Tundra Double Cab',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Yaris',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Yaris iA',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','86',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Toyota','Mirai',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volkswagen','Atlas',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volkswagen','Beetle',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volkswagen','Golf',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volkswagen','Golf Alltrack',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volkswagen','Golf GTI',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volkswagen','Golf R',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volkswagen','Golf SportWagen',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volkswagen','Jetta',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volkswagen','Passat',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volkswagen','Tiguan',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volkswagen','Tiguan Limited',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volvo','S60',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volvo','S90',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volvo','V60',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volvo','V90',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volvo','XC60',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
INSERT INTO vehicle_list(year,make,model,id_vehicle_class) VALUES (2018,'Volvo','XC90',(SELECT id FROM vehicle_class ORDER BY RANDOM() LIMIT 1));
